# Generated by Django 4.1.5 on 2023-04-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='images', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
